"""Checks that the Alembic migrations and the models agree, on throwaway Postgres databases.

1. Creates an empty scratch database and runs `alembic upgrade head`.
2. Runs `alembic check`: fails if the models have changes no migration covers.
3. Builds a second scratch database with SQLModel.metadata.create_all and compares the two schemas
   (columns, types, nullability, defaults, constraints, indexes, enum types and labels, sequences).
4. Runs `alembic downgrade base` on the first and checks nothing is left behind.
Both scratch databases are dropped at the end. Uses the server in DATABASE_URL, which must be local.

Usage (from the project root):  python scripts/check_migrations.py
Exit code: 0 if everything matches, 1 otherwise.
"""
import os
import sys
import uuid
from pathlib import Path

from dotenv import load_dotenv
from sqlalchemy import create_engine, text
from sqlalchemy.engine import make_url

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ALLOWED_HOSTS = {"localhost", "127.0.0.1"}


def schema_snapshot(engine) -> dict:
    """Everything about the public schema that a migration could get wrong, except alembic_version."""
    queries = {
        "columns": """SELECT table_name, column_name, data_type, udt_name, character_maximum_length,
                             numeric_precision, numeric_scale, is_nullable, column_default
                        FROM information_schema.columns
                       WHERE table_schema = 'public' AND table_name <> 'alembic_version'""",
        "constraints": """SELECT conrelid::regclass::text, conname, contype, pg_get_constraintdef(oid)
                            FROM pg_constraint
                           WHERE connamespace = 'public'::regnamespace AND conrelid::regclass::text <> 'alembic_version'""",
        "indexes": """SELECT tablename, indexname, indexdef FROM pg_indexes
                       WHERE schemaname = 'public' AND tablename <> 'alembic_version'""",
        "enums": """SELECT t.typname, string_agg(e.enumlabel, ',' ORDER BY e.enumsortorder)
                      FROM pg_type t JOIN pg_enum e ON e.enumtypid = t.oid GROUP BY t.typname""",
        "sequences": """SELECT sequence_name, data_type, start_value, increment FROM information_schema.sequences
                         WHERE sequence_schema = 'public'""",
    }
    with engine.connect() as conn:
        return {name: sorted(tuple(map(str, row)) for row in conn.execute(text(sql)).all()) for name, sql in queries.items()}


def tables(engine) -> list[str]:
    with engine.connect() as conn:
        return sorted(conn.execute(text("SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'")).scalars())


def main() -> int:
    load_dotenv(PROJECT_ROOT / ".env")
    raw_url = os.environ.get("DATABASE_URL")
    if not raw_url:
        print("DATABASE_URL is not set.")
        return 1
    base = make_url(raw_url)
    if base.host not in ALLOWED_HOSTS or {"host", "hostaddr"} & set(base.query):
        print(f"Refusing to run: DATABASE_URL host is {base.host!r}; scratch databases are only created on localhost.")
        return 1

    sys.path.insert(0, str(PROJECT_ROOT))
    from alembic import command
    from alembic.config import Config
    from alembic.util.exc import AutogenerateDiffsDetected
    from sqlmodel import SQLModel
    import main as app_module  # noqa: F401  registers the models

    cfg = Config(str(PROJECT_ROOT / "alembic.ini"))
    admin = create_engine(base.set(database="postgres"), isolation_level="AUTOCOMMIT")
    names = [f"invai_migcheck_{uuid.uuid4().hex[:8]}" for _ in range(2)]
    problems = []
    try:
        for name in names:
            with admin.connect() as conn:
                conn.execute(text(f'CREATE DATABASE "{name}"'))
        migrated_url, created_url = (base.set(database=name) for name in names)

        # 1. Migrations to head on an empty database (env.py reads DATABASE_URL)
        os.environ["DATABASE_URL"] = migrated_url.render_as_string(hide_password=False)
        command.upgrade(cfg, "head")

        # 2. Models vs migrations
        try:
            command.check(cfg)
            print("OK   alembic check: the migrations at head match the models")
        except AutogenerateDiffsDetected as exc:
            problems.append(f"alembic check found changes no migration covers:\n{exc}")

        # 3. Same schema as create_all
        migrated_engine, created_engine = create_engine(migrated_url), create_engine(created_url)
        SQLModel.metadata.create_all(created_engine)
        migrated, created = schema_snapshot(migrated_engine), schema_snapshot(created_engine)
        schema_matches = True
        for part in migrated:
            only_migrated = sorted(set(migrated[part]) - set(created[part]))
            only_created = sorted(set(created[part]) - set(migrated[part]))
            if only_migrated or only_created:
                schema_matches = False
                problems.append(f"{part} differ:\n  only in migrated: {only_migrated}\n  only in create_all: {only_created}")
        if schema_matches:
            counts = ", ".join(f"{len(v)} {k}" for k, v in migrated.items())
            print(f"OK   upgrade head == create_all ({counts})")

        # 4. Downgrade leaves nothing behind
        command.downgrade(cfg, "base")
        leftover_tables = [t for t in tables(migrated_engine) if t != "alembic_version"]
        leftover_enums = schema_snapshot(migrated_engine)["enums"]
        if leftover_tables or leftover_enums:
            problems.append(f"downgrade base left tables {leftover_tables} and enum types {leftover_enums}")
        else:
            print("OK   downgrade base removes every table and enum type")
        migrated_engine.dispose(); created_engine.dispose()
    except Exception as exc:
        problems.append(f"{type(exc).__name__}: {exc}")
    finally:
        with admin.connect() as conn:
            for name in names:
                conn.execute(text(f'DROP DATABASE IF EXISTS "{name}" WITH (FORCE)'))
        admin.dispose()

    for problem in problems:
        print(f"FAIL {problem}")
    print("migrations check:", "passed" if not problems else f"FAILED ({len(problems)} problem(s))")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
